version: '3'

services:
  db:
    image: mongodb
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    hostname: web
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
